language: java
sudo: false
addons:
  apt:
    packages:
    - php5-cli
    - mono-complete
jdk:
  - openjdk6
before_install:
  - mkdir -p ~/.m2/
  - cp -a ./settings.xml ~/.m2/
script:
  - mvn deploy
