language: java
sudo: false
addons:
  apt:
    packages:
    - php5-cli
    - mono-complete
    - gnupg
jdk:
  - openjdk6
before_install:
  - mkdir -p ~/.m2/ ~/.gnupg/
  - cp -a ./tools/settings.xml ~/.m2/
  - echo "${ENCRYPTION_PASSWORD}" | gpg --passphrase-fd 0 -o ~/.gnupg/secring.gpg ./tools/secring.gpg.enc
script:
  - mvn deploy
